apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "employee.name" . }}-configmap
  namespace: {{ include "employee.namespace" . }}

data:
  {{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}