{{- if .Values.persistentVolumeClaim.enabled }}

apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: {{ include "employee.name" . }}-pvc
  namespace: {{ include "employee.namespace" . }}

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.storage }}

{{- end }}